// Builds the themed Bootstrap stylesheets: one left-to-right, one right-to-left.
//
// Why a script and not just an entry in angular.json: Bootstrap does not use
// logical properties. Its right-to-left support is a second stylesheet produced
// by running the compiled CSS through RTLCSS, and the Angular CLI has no step
// that turns one stylesheet into two. So this compiles src/theme/bootstrap.scss
// once, writes it as-is, and writes an RTLCSS-flipped copy beside it. angular.json
// then bundles both (not injected) and the app picks one by language.
//
//   node scripts/build-theme.mjs           build once
//   node scripts/build-theme.mjs --watch   rebuild whenever src/theme changes
//   node scripts/build-theme.mjs --check   fail if the committed output is stale
//
// The output is committed so a plain `ng serve` works without running this
// first; `npm start` / `npm run build` regenerate it anyway, and --check keeps
// the committed copy honest.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as sass from 'sass';
import rtlcss from 'rtlcss';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const themeDir = path.join(root, 'src', 'theme');
const entry = path.join(themeDir, 'bootstrap.scss');
const outDir = path.join(themeDir, 'generated');
const outputs = {
  ltr: path.join(outDir, 'bootstrap.ltr.css'),
  rtl: path.join(outDir, 'bootstrap.rtl.css'),
};

const HEADER =
  '/* GENERATED by scripts/build-theme.mjs from src/theme — do not edit by hand. */\n';

function compile() {
  const { css } = sass.compile(entry, {
    loadPaths: [path.join(root, 'node_modules'), themeDir],
    style: 'expanded',
    // Bootstrap 5.3 predates Sass's module system; its deprecation warnings are
    // not ours to fix and would bury real errors.
    quietDeps: true,
  });
  return {
    ltr: HEADER + css,
    rtl: HEADER + rtlcss.process(css),
  };
}

function write() {
  const started = Date.now();
  const built = compile();
  fs.mkdirSync(outDir, { recursive: true });
  for (const dir of ['ltr', 'rtl']) {
    fs.writeFileSync(outputs[dir], built[dir]);
  }
  const kb = (s) => `${Math.round(Buffer.byteLength(s) / 1024)} KB`;
  console.log(`theme built in ${Date.now() - started} ms — ltr ${kb(built.ltr)}, rtl ${kb(built.rtl)}`);
}

function check() {
  const built = compile();
  const stale = ['ltr', 'rtl'].filter(
    (dir) => !fs.existsSync(outputs[dir]) || fs.readFileSync(outputs[dir], 'utf8') !== built[dir],
  );
  if (stale.length) {
    console.error(`theme is stale (${stale.join(', ')}) — run: npm run theme`);
    process.exit(1);
  }
  console.log('theme is up to date');
}

function watch() {
  write();
  let timer;
  fs.watch(themeDir, { recursive: true }, (_event, file) => {
    if (!file || file.startsWith('generated')) return;
    clearTimeout(timer);
    timer = setTimeout(() => {
      try {
        write();
      } catch (e) {
        // Keep watching after a Sass error rather than exiting mid-edit.
        console.error(e.message);
      }
    }, 100);
  });
  console.log('watching src/theme …');
}

const mode = process.argv[2];
try {
  if (mode === '--check') check();
  else if (mode === '--watch') watch();
  else write();
} catch (e) {
  console.error(e.message);
  process.exit(1);
}
